version: "3.7"
services:
    broadcast:
        build:
            context: .
        devices:
            - /dev/vchiq:/dev/vchiq
        privileged: true
        volumes:
            - type: tmpfs
              target: /broadcast-temp
              tmpfs:
                  size: 64m
            - type: volume
              source: video
              target: /broadcast-video
            - /opt/vc:/opt/vc:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: always
    nginx:
        image: nginx:1.18
        volumes:
            - type: volume
              source: video
              target: /broadcast-video
            - type: bind
              source: ./nginx.conf
              target: /etc/nginx/nginx.conf
        ports: 
            - 80:80
        restart: always
volumes:
    video:
