version: "3.7"
services:
    broadcast:
        build:
            context: .
            args:
                - APP_TZ=$TZ
        devices:
            - /dev/vchiq:/dev/vchiq
        privileged: true
        volumes:
            - type: tmpfs
              target: /broadcast-temp
              tmpfs:
                  size: 64m
            - /opt/vc:/opt/vc:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: always
